# Generated by Django 2.1.7 on 2019-05-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fract', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='liked_images',
            field=models.ManyToManyField(to='fract.Image'),
        ),
    ]
